from __future__ import annotations
import json, shutil
from datetime import datetime
import nibabel as nib
import numpy as np
from rich.console import Console
from rich.table import Table
from utils_paths import OUTPUT_DIR, RAW_DIR, REPORTS_DIR, ensure_project_dirs, provisional_folder, ATLAS_NAME

console = Console()
ATLAS_TITLE = "Paxinos-Watson Rat Brain Atlas, provisional BrainGlobe test package"
RESOLUTION_UM = 40

def make_label_edge_reference(annotation):
    ann = annotation.astype(np.int32)
    edge = np.zeros(ann.shape, dtype=bool)
    edge[:-1,:,:] |= ann[:-1,:,:] != ann[1:,:,:]
    edge[1:,:,:] |= ann[:-1,:,:] != ann[1:,:,:]
    edge[:,:-1,:] |= ann[:,:-1,:] != ann[:,1:,:]
    edge[:,1:,:] |= ann[:,:-1,:] != ann[:,1:,:]
    edge[:,:,:-1] |= ann[:,:,:-1] != ann[:,:,1:]
    edge[:,:,1:] |= ann[:,:,:-1] != ann[:,:,1:]
    return np.where(edge, 50000, np.where(ann > 0, 12000, 0)).astype(np.uint16)

def validate_annotation_structures(annotation, structures):
    used_ids = set(np.unique(annotation[np.isfinite(annotation)]).astype(int).tolist())
    structure_ids = set(int(s["id"]) for s in structures)
    ids_without_structure = sorted(x for x in used_ids if x not in structure_ids and x != 0)
    structures_without_voxels = sorted(x for x in structure_ids if x not in used_ids and x != 997000)
    return {"used_id_count_including_background": len(used_ids), "structure_count": len(structures), "ids_without_structure": ids_without_structure, "structures_without_voxels_count": len(structures_without_voxels), "structures_without_voxels_sample": structures_without_voxels[:50], "passed": len(ids_without_structure) == 0}

def main() -> int:
    ensure_project_dirs()
    annotation_src = RAW_DIR / "Paxinos_Watson_Atlas.nii.gz"
    structures_src = OUTPUT_DIR / "structures_draft_flat.json"
    if not annotation_src.exists():
        raise FileNotFoundError(f"Missing annotation volume: {annotation_src}")
    if not structures_src.exists():
        raise FileNotFoundError(f"Missing structures file: {structures_src}")

    out_root = provisional_folder()
    if out_root.exists():
        shutil.rmtree(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    img = nib.load(str(annotation_src))
    raw = np.asanyarray(img.dataobj)
    annotation = np.round(raw).astype(np.uint32)
    annotation_img = nib.Nifti1Image(annotation, img.affine)
    annotation_img.header.set_zooms(img.header.get_zooms()[:3])
    annotation_path = out_root / "annotation.nii.gz"
    nib.save(annotation_img, str(annotation_path))

    reference = make_label_edge_reference(annotation)
    reference_img = nib.Nifti1Image(reference, img.affine)
    reference_img.header.set_zooms(img.header.get_zooms()[:3])
    reference_path = out_root / "reference.nii.gz"
    nib.save(reference_img, str(reference_path))

    structures = json.loads(structures_src.read_text(encoding="utf-8"))
    structures_path = out_root / "structures.json"
    structures_path.write_text(json.dumps(structures, indent=2, ensure_ascii=False), encoding="utf-8")
    validation = validate_annotation_structures(annotation, structures)

    metadata = {"name": ATLAS_NAME, "title": ATLAS_TITLE, "species": "Rattus norvegicus", "resolution": [RESOLUTION_UM, RESOLUTION_UM, RESOLUTION_UM], "orientation": "LPI", "source_dataset": {"name": "BlueBrainHeadModels", "version": "v1", "published": "2024-04-04", "doi": "10.5281/zenodo.10926947"}, "source_files": {"annotation": "Paxinos_Watson_Atlas.nii.gz", "labels": "Paxinos_Watson_Labels.txt", "cortex_labels": "Paxinos_Watson_Labels_Cortex.txt"}, "reference_strategy": "provisional_label_edge_reference_generated_from_annotation_boundaries", "status": "provisional_technical_test_package", "warning": "This is not a final validated BrainGlobe atlas. It is a first local package for format and loading tests.", "files": {"reference": "reference.nii.gz", "annotation": "annotation.nii.gz", "structures": "structures.json"}}
    metadata_path = out_root / "metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")
    (out_root / "README.md").write_text(f"# {ATLAS_TITLE}\\n\\nProvisional technical package generated by rat-paxinos-brainglobe-builder.\\n\\nSource dataset: BlueBrainHeadModels v1, DOI 10.5281/zenodo.10926947.\\n", encoding="utf-8")

    report = {"generated_at": datetime.now().isoformat(timespec="seconds"), "atlas_folder": str(out_root), "annotation_shape": list(annotation.shape), "annotation_dtype": str(annotation.dtype), "annotation_unique_count": int(np.unique(annotation).size), "reference_shape": list(reference.shape), "reference_dtype": str(reference.dtype), "metadata": metadata, "validation": validation, "next_step": "Run validate_provisional_atlas_package.py and then build official candidate layout."}
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    (REPORTS_DIR / "provisional_brainglobe_build_report.json").write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    lines = ["Provisional BrainGlobe test atlas build report", "="*72, f"Generated: {report['generated_at']}", f"Atlas folder: {out_root}", "", f"Annotation shape: {report['annotation_shape']}", f"Annotation dtype: {report['annotation_dtype']}", f"Annotation unique IDs: {report['annotation_unique_count']}", f"Reference shape: {report['reference_shape']}", f"Reference dtype: {report['reference_dtype']}", "", "Validation:", f"- Used IDs without structure: {len(validation['ids_without_structure'])}", f"- Structures without voxels: {validation['structures_without_voxels_count']}", f"- Passed: {validation['passed']}"]
    (REPORTS_DIR / "provisional_brainglobe_build_report.txt").write_text("\\n".join(lines), encoding="utf-8")

    table = Table(title="Provisional BrainGlobe test atlas")
    table.add_column("Metric"); table.add_column("Value")
    table.add_row("Atlas folder", str(out_root))
    table.add_row("Annotation shape", str(annotation.shape))
    table.add_row("Unique IDs", str(report["annotation_unique_count"]))
    table.add_row("Validation passed", str(validation["passed"]))
    table.add_row("IDs without structure", str(len(validation["ids_without_structure"])))
    console.print(table)
    console.print(f"[green]Wrote:[/green] {REPORTS_DIR / 'provisional_brainglobe_build_report.txt'}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
